name: Snapshot
on:
  workflow_dispatch:

jobs:
  snapshot:
    name: Release snapshot version
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: ./.github/actions/install-deps

      - name: Publish Snapshot
        continue-on-error: true
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          snapshot=$(git branch --show-current | tr -cs '[:alnum:]-' '-' | tr '[:upper:]' '[:lower:]' | sed 's/-$//')
          npm config set "//registry.npmjs.org/:_authToken" "$NPM_TOKEN"
          git reset --hard origin/main
          pnpm clean
          pnpm changeset version --no-git-tag --snapshot $snapshot
          pnpm changeset:prepublish
          pnpm changeset publish --no-git-tag --snapshot $snapshot --tag $snapshot
